# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tutkimusblogi
email: paspah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Täällä pidän kirjaa tutkimusprosessini etenemisestä. Tavoitteena väitöskirja yhteiskuntatieteiden alalta.Tutkimuskohteena isyys. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter: @paspah

# Build settings
markdown: kramdown
